### PR TITLE
Prompt the user to delete the profile when deleting its last site

### LINKED ISSUE #407: Option to delete profile when deleting its last PWA
### Problem Description

When deleting a PWA, the profile used for it isn't deleted, even if it doesn't host any other PWAs

### Proposed Solution

A enabled-by-default checkbox that says "Delete the associated profile ?" when deleting the last PWA of a profile (if there are other PWAs in the profile, the checkbox would not appear)

I'd be ready to submit a PR for this (no promise tho), but I want your approval first, so I'm waiting for your response

### PR DESCRIPTION
**Pull request by iTrooz**
Fix #407

### CODE REVIEW

**Comment by iTrooz** [comment]
Draft because I modified a message I'm not sure about (https://github.com/filips123/PWAsForFirefox/issues/407#issuecomment-1815225740)

**Comment by iTrooz** [comment]
Ready for review

**Review by filips123 — APPROVED** [review]
Thank you!

**Comment by iTrooz** [comment]
You're welcome, thanks for answering quickly :)

**Pull request merged**
