### PR TITLE
Make the extension multilingual

### PR DESCRIPTION
**Pull request by surapunoyousei**
Multilingualization is underway.

write if you have anything

### CODE REVIEW

**Comment by filips123** [comment]
Thanks! Let me know when this is finished. I might then merge all localization-related PRs into a separate branch, so they can be released together and I can work on other changes in the meantime.

Also, you have to use Yarn for dependency installation, otherwise, a separate `package-lock.json` is generated. I don't know why `yarn.lock` got changed, maybe it's because you have a different version.

You can also use `yarn lint` and `yarn fix` to check all those linting errors from GitHub Actions.

**Comment by surapunoyousei** [comment]
I used npm because yarn was throwing an error when install dependenciesand not working. Delete it. I was able to use yarn to run it, so I'll adjust it well

**Comment by surapunoyousei** [comment]
I finished setup & update sites localize.

**Comment by filips123** [comment]
I've changed the base branch to `wip-localization-extension` so I can do a few more tweaks and release full extension localization when it's ready at once. So, please also submit any other extension localization-related PRs to that branch. I've been also working on the Crowdin setup.

This work seems mostly fine, but I have a few comments. First, I would like to make translation keys/IDs a bit more consistent (camel case, more consistent wording, etc.), but I will do this later after this PR is merged.

Another thing is that I'm not sure about having HTML inside translation messages. The first problem is that this can introduce security problems if translations are untrusted or general issues if they are malformed. The second problem is that now all links are also included in translations, so, for example, if I need to change a link, it also needs to be changed in all other translations. I don't know what the best solution for this is. I may have to check some other extensions to see what they are doing...

**Comment by surapunoyousei** [comment]
I'll adjust the localize ID.

**Comment by filips123** [comment]
I've checked how some popular extensions handle localization/internationalization. It appears that this is not actually that common (most extensions that I've checked just use plain-text translations, which is quite surprising) and there isn't any definite/recommended way.

So, this is quite a long comment about existing solutions and how I think this could be implemented.

---

uBlock Origin is just using HTML in messages, but [allowing only specific elements](https://github.com/gorhill/uBlock/blob/master/src/js/i18n.js) (those for styling text and links) and constructing them in a way that does not trigger "Unsafe assignment to innerHTML". This is fine for security, but it still has a problem that `href` and other similar attributes are included in translations.

Some other extensions define their own custom placeholders, place them in translation messages where custom elements should be, and replace them after getting translated strings with HTML elements with JS. However, this does not seem that nice and can probably become quite messy.

I've also found [another library (Localizer)](https://github.com/TinyWebEx/Localizer#keeping-child-elements-in-html) that supports keeping child elements in HTML. This is nice because there are no security problems (all elements are hardcoded in HTML) and `href` attributes are not stored in translations. However, this requires that each sub-element is stored in its own translation key, which can also become annoying and messy, especially in messages where there are a lot of short styling/link tags. For example, in [this message](https://github.com/filips123/PWAsForFirefox/blob/main/extension/src/setup/install.html#L33), each of those `a` tag values would need to be in its own translation message.

I've then checked how Fluent handles this. It supports some [DOM overlays](https://github.com/projectfluent/fluent.js/wiki/DOM-Overlays) which support both text/styling elements and links. For text elements, it's kinda similar to uBlock's way of handling things (they are automatically constructed) and for links, it's similar to Localizer (actual tags, including `href` attributes, are still inside HTML) while not requiring separate translation messages. The problem is that extensions do not support Fluent natively. I don't know if there are any existing libraries that work with webextension translations and support this.

---

Based on those analyses, I think that a combination of Localizer, uBlock and Fluent solutions could work.

For text/styling elements, it should work like uBlock/Fluent. So, safe HTML elements like `<em>` and `<strong>` are allowed in translations and safely constructed when displaying translations.

For links (`<a>`) and other similar elements, it should work like Fluent. This means that the element needs to be defined inside the HTML file (including its `href` attribute), but the translation can still reference and translate it.

For "untranslatable" messages (commands and paths), it should use something similar to Localizer. So, those messages are hard-coded inside HTML file, but translation messages can reference them (with placeholders or tags?) to customize their position and surrounding words.

---

For example, when translating/constructing the following message:

```html
<li>The project logo is based on <a href="https://www.svgrepo.com/svg/40267/fox">the &quot;Fox SVG Vector&quot; icon</a> and <a href="https://github.com/webmaxru/progressive-web-apps-logo">the community-introduced PWA logo</a>, both dedicated to the public domain using <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0</a>.</li>
```

The HTML file would contain just link definitions:

```html
<li data-i18n="projectLogoLicenseNotice">
  <a href="https://www.svgrepo.com/svg/40267/fox" data-i18n-name="foxSvgVectorURL" />
  <a href="https://github.com/webmaxru/progressive-web-apps-logo" data-i18n-name="progressiveWekAppsLogoURL" />
  <a href="https://creativecommons.org/publicdomain/zero/1.0/" data-i18n-name="cc0URL" />
```

And translation message would be:

```html
The project logo is based on <a data-i18n-name="foxSvgVectorURL">the &quot;Fox SVG Vector&quot; icon</a> and <a data-i18n-name="progressiveWekAppsLogoURL">the community-introduced PWA logo</a>, both dedicated to the public domain using <a data-i18n-name="cc0URL">CC0</a>.
```

---

And for translating/constructing the following message:

```html
<li>Install the package using choco: <kbd>choco install firefoxpwa --version <span class="connector-project-version"></span></kbd></li>
```

The HTML file would contain the untranslatable command:

```html
<li data-i18n="installChocoStep2">
<kbd data-i18n-name="chocoCommand">choco install firefoxpwa --version <span class="connector-project-version"></span></kbd>
</li>
```

And translation message would be one of the following:

```html
<!-- If we decide to use placeholder-based approach -->
Install the package using choco: $chocoCommand$

<!-- If we decide to use HTMl tag-based approach -->
Install the package using choco: <kbd data-i18n-name="chocoCommand" />
```

---

I'm not sure how hard would it be to implement all this and if it's feasible. But considering how many things this would implement, it might even be useful to make it a separate library that others can also use.

If this is too complex to implement, uBlock's solution also seems good enough. This solution can then be implemented later if needed.

**Comment by surapunoyousei** [comment]
After looking at the appropriate solution based on the method you provided, I decided to declare the URL in JS or HTML and use placeholders to have only one place to declare the URL.  

Also, I would like to solve the security problem by reviewing the contents of the message passed in blacklist format, checking for tags that should not be used, and executing only when the check succeeds.

PS: In xBrowserSync, etc., the URL is embedded in the direct translation, and I saw places where the link destination was changed for each language.  Note that the review was run by an administrator.

**Comment by filips123** [comment]
That should be fine.

But for checking HTML in translations, it's probably better to only allow a specific list of tags (`em`, `strong`, `b`, `i`, `kbd`, `code`, `span`), while other get turned into text. I think this is also similar to what uBlock and Fluent DOM Overlays are doing, although their code cannot be copied due to licence.

**Comment by surapunoyousei** [comment]
I'll make one based on the suggestions you gave me.

**Comment by surapunoyousei** [comment]
URLs can now be replaced while including some HTML as follows
image

I interrupt here because it is possible that your naming sense does not match mine. Let me know if you have any suggestions.
image

In addition, only the following tags are allowed, and direct URL attachments will also be converted to plain text
image

**Comment by filips123** [comment]
This looks fine.

**Comment by surapunoyousei** [comment]
Finished!

**Review by filips123 — APPROVED** [review]
This looks fine. I'll merge it to a separate branch and then change those IDs and a few other small changes. However, I'll be busy over the next month, so I'm not sure yet when this will be done and released.

Thanks for your help!

**Comment by surapunoyousei** [comment]
Thank you very much. We will now research multilingualization on the native side.

We are not sure when that will be, but will let you know when Fluent is available.

PS: We apologize for creating unnecessary files.

**Pull request merged**
