### PR TITLE
Treat localhost as secure context

### PR DESCRIPTION
**Pull request by iTrooz**
Related: https://github.com/filips123/PWAsForFirefox/pull/421

This PR will allow localhost-related URLs to be treated as secure context

### CODE REVIEW

**Review by filips123 — APPROVED** [review]
Thanks!

**Comment by iTrooz** [comment]
Hey, just wondering:
I checked this PR today for the first time since I submitted it, and I now see you pushing another commit to it.

Did github notify you that I looked at the PR or something ?

**Comment by filips123** [comment]
No, I just didn't have much time to review it until today. In that commit, I've just slightly changed the comments so they are more consistent with the others.

**Comment by iTrooz** [comment]
Ok ! Well, thank you

**Pull request merged**
